-- AlterEnum
ALTER TABLE `Content` MODIFY `type` ENUM('FILM', 'GLOSSARY', 'CINEMA_SHOW', 'ARTICLE', 'RESEARCH', 'TRANSLATION', 'VIRAL_ESCAPE_LINES', 'INTERVIEW', 'PODCAST', 'EVENT', 'OTHER') NOT NULL;
