require("dotenv").config();
const prisma = require("../../../../src/db");

const films = [
  { title: "Machuca", youtubeId: "OsLL2uLaEDA", director: "Andrés Wood", genre: "Drama", country: "Chile", year: "2003", duration: "120 min", description: "O Golpe de Pinochet interrompe um experiência do diretor de um colégio de elite na capital chilena, que admite de forma gratuita no estabelecimento alguns filhos de famílias de trabalhadores." },
  { title: "Manhã Cinzenta", youtubeId: "3p-ozsRH0xY", director: "Olney São Paulo", genre: "Documentário", country: "Brasil", year: "1969", duration: "40 min", description: "Baseado em conto homônimo de Olney São Paulo, o filme é uma alegoria de regimes autoritários, e é ambientado em um país fictício da América Latina. Retrata um casal de estudantes que segue para uma passeata onde o rapaz, um militante, lidera um comício. Eles são presos, torturados na prisão e sofrem um inquérito absurdo dirigido por um robô e um cérebro eletrônico." },
  { title: "Marãiwatsédé", youtubeId: "r5i3i8n6w-0", duration: "30 min", description: "Com 30 minutos de duração, o filme conta a história da luta de mais de 40 anos dos Xavante para recuperar a posse do território de onde foram removidos à força em 1966. A desocupação forçada e mais de 263 índios morreram durante a remoção." },
  { title: "Marighella", youtubeId: "URGkEaDngcg", director: "Isa Grinspum Ferraz", genre: "Documentário", country: "Brasil", year: "2012", duration: "100 min", description: "Dirigido pela sobrinha de Marighella, o filme é uma construção histórica e afetiva do homem considerado o inimigo número 1 da ditadura militar brasileira. Este líder comunista e parlamentar foi preso e torturado, e tornou-se famoso por ter redigido o Manual do Guerrilheiro Urbano." },
  { title: "Marighella – Retrato Falado do Guerrilheiro", youtubeId: "eeJuuS3bebU", director: "Silvio Tendler", genre: "Documentário", country: "Brasil", year: "2011", duration: "55 min", description: "O documentário conta a história, as polêmicas, as vitórias e derrotas de Carlos Marighella, um dos líderes da luta armada contra a ditadura militar no Brasil." },
  { title: "Memória para Uso Diário", youtubeId: "Ys4781EYPBU", director: "Beth Formagini", genre: "Documentário", country: "Brasil", year: "2007", duration: "84 min", description: "Nosso fio condutor é Ivanilda, que durante 31 anos procurou nos arquivos sinais do seu marido, um desaparecido político. Suas idas e vindas se trançam com as ações de militantes e parentes das vitimas da ditadura e da violência policial dos dias de hoje que vão desvelando outros fios pelas ruas e cemitérios clandestinos do Rio. Eles pertencem ao Grupo Tortura Nunca Mais /RJ e interagem entre a lembrança traumática e o esquecimento no trabalho de trazer à tona a memória de fatos recentes, revelando a seletividade da história oficial e de construir uma memória política. Pensam o passado para que se possam libertar o futuro dos fantasmas que ainda nos perseguem no presente." },
  { title: "Memórias Clandestinas", youtubeId: "j0wW2DCnN9o", director: "Maria Thereza Azevedo", genre: "Documentário", country: "Brasil", year: "2004", duration: "70 min", description: "Documentário sobre a primeira mulher de Francisco Julião, Alexina Crespo, e sua atuação na organização das Ligas Camponesas, movimento social agrário que lutou pela posse da terra e o fim da exploração do trabalhador rural entre 1950 e 1964. Alexina e seus quatro filhos falam das peripécias ocorridas desde o seu casamento com Francisco Julião, passando pela organização das ligas, a guerrilha, o golpe e o exílio, um trabalho que ficou no silêncio, na coxia e na clandestinidade." },
  { title: "Memórias da Repressão", youtubeId: "DN9Qt1Eh484", genre: "Documentário", country: "Brasil", year: "1991", duration: "17 min", description: "Produzido pela Secretaria de Comunicação social do Paraná em 1991. O documentário representa o importante momento de abertura dos Arquivos da DOPS no Paraná." },
  { title: "Memórias de Mujeres", youtubeId: "klc7Ws6ZK2E", director: "Virginia Martinez", genre: "Documentário", country: "Uruguai", year: "2005", duration: "31 min", description: "O Presídio de Punta Rieles foi o lugar onde estiveram encarceradas, entre 1973 e 1985, a maioria das presas políticas da ditadura civil-militar uruguaia. O documentário tenta reconstruir a vida no Presídio, tal como é recordada hoje por algumas das centenas de mulheres que ali estiveram e resistiram à pretensão dos militares de destruí-las física, psíquica e ideologicamente." },
  { title: "Memórias Femininas da Luta contra a Ditadura Militar", youtubeId: "YWtuhUsn5ao", director: "Maria Paula Araujo (coordenação)", genre: "Documentário", country: "Brasil", year: "2015", duration: "51 min", description: "O documentário é um projeto do Laboratório de Estudos do Tempo Presente (Instituto de História/UFRJ) que aborda a trajetória de mulheres que atuaram na resistência à ditadura militar brasileira a partir de depoimentos do acervo \"Marcas da memória: história oral da anistia no Brasil\". Apoio: Universidade Federal do Rio de Janeiro e Comissão de Anistia do Ministério da Justiça." },
  { title: "MPB nos Tempos de Ditadura", youtubeId: "P4BNAZmok6o", genre: "Documentário", description: "Documentário sobre diversos autores da MPB acerca dos desafios enfrentados por conta da censura, as prisões e as histórias que cercam desde as experiências como artistas aqui no Brasil e o exílio." },
];

async function main() {
  const importer = await prisma.user.findUnique({ where: { email: "importacao-acervo@lace.local" } });
  if (!importer) throw new Error("Usuário de importação do acervo não encontrado.");
  for (const film of films) {
    const externalUrl = `https://www.youtube.com/watch?v=${film.youtubeId}`;
    const metadata = { youtubeId: film.youtubeId, videoProvider: "youtube", imageUrl: `https://img.youtube.com/vi/${film.youtubeId}/hqdefault.jpg`, director: film.director, genre: film.genre, country: film.country, year: film.year, duration: film.duration };
    const existing = await prisma.content.findFirst({ where: { type: "FILM", title: film.title } });
    const data = { title: film.title, description: film.description, type: "FILM", researcherName: "Equipe LACE", externalUrl, metadata, published: true, createdById: importer.id };
    if (existing) await prisma.content.update({ where: { id: existing.id }, data });
    else await prisma.content.create({ data });
  }
  console.log(`${films.length} filmes da letra M importados.`);
}

main().catch((error) => { console.error(error); process.exitCode = 1; }).finally(() => prisma.$disconnect());
