require("dotenv").config();
const prisma = require("../../../../src/db");

const films = [
  { title: "O Ano que Meus Pais Saíram de Férias", youtubeId: "yplwrQIWgIw", director: "Cao Hamburger", genre: "Drama", country: "Brasil", year: "2006", duration: "105 min", description: "1970. Mauro (Michel Joelsas) é um garoto mineiro de 12 anos, que adora futebol e jogo de botão. Um dia, sua vida muda completamente, já que seus pais saem de férias de forma inesperada e sem motivo aparente para ele. Na verdade, os pais de Mauro foram obrigados a fugir da perseguição política, tendo que deixá-lo com o avô paterno (Paulo Autran). Porém o avô enfrenta problemas, o que faz com que Mauro tenha que ficar com Shlomo (Germano Haiut), um velho judeu solitário que é vizinho do avô de Mauro." },
  { title: "O Beijo da Mulher Aranha", youtubeId: "m-s1XO17x7E", director: "Héctor Babenco", genre: "Drama", country: "Brasil", year: "1986", duration: "120 min", description: "Em uma prisão na América do Sul, dois prisioneiros dividem a mesma cela. Um é homossexual e está preso por comportamento imoral e o outro é um prisioneiro político. O primeiro, para fugir da triste realidade que o cerca, inventa filmes cheios de mistério e romance, mas o outro tenta se manter o mais politizado possível em relação ao momento que vive. Mas esta convivência faz com que os dois homens se compreendam e se respeitem." },
  { title: "O Bom Burguês", youtubeId: "UE641Y5uxA8", director: "Oswaldo Caldeira", genre: "Drama", country: "Brasil", year: "1979", duration: "100 min", description: "O Bancário Lucas financia organizações políticas esquerdistas com o dinheiro que desvia do banco em que trabalha. Usando seu cargo de confiança, Lucas abre contas fantasmas, autoriza a compensação de cheques frios e acumula uma fortuna. Com o tempo, sua ambição faz com que comece a se envolver com grandes empresários milionários que patrocinam a repressão militar da ditadura." },
  { title: "O Desafio", youtubeId: "hcggtO2bmvo", director: "Paulo César Saraceni", genre: "Drama", country: "Brasil", year: "1965", duration: "90 min", description: "Logo após o golpe militar de 1964, Ada é esposa de um rico empresário industrial, e se envolve em um caso amoroso com o jornalista de esquerda Marcelo, que trabalha em uma revista. O filme retrata os desafio, durante o regime militar, de se envolver em um relacionamento com alguém de classe diferente." },
  { title: "O Dia que Durou 21 Anos", youtubeId: "ltawI64zBEo", director: "Camilo Galli Tavares", genre: "Documentário", country: "Brasil", year: "2012", duration: "77 min", description: "O documentário O DIA QUE DUROU 21 ANOS narra a trama construída para derrubar o poder do presidente João Goulart (1963-1964). Participaram desta articulação a Central Intelligence Agency (CIA), o presidente Lindon Johnson (EUA) e sua assessoria, o embaixador dos EUA Lincoln Gordon, os militares brasileiros, e empresários brasileiros e estrangeiros, ligados ao capital internacional. O documentário denuncia, por meio de consulta a arquivos importantes nos Estados Unidos, que a finalidade deste país era intervir diretamente na política nacional, construindo minuciosamente o golpe de Estado, que levou à ditadura militar-empresarial no Brasil (1964-1989)." },
  { title: "O Expurgado", youtubeId: "4njP3dUDWKw", description: null },
  { title: "O Fim do Esquecimento", vimeoId: "205560464", externalUrl: "https://vimeo.com/205560464", director: "Renato Tapajós", genre: "Documentário", country: "Brasil", year: "2012", duration: "54 min", description: "O filme procura personagens que participaram do Tribunal de Tiradentes e outros que se destacaram na luta pelos Direitos Humanos, para retomar a questão da Doutrina de Segurança Nacional, depois de três décadas. Investiga os resquícios daquela doutrina nos dias de hoje, aborda a tentativa das classes dominantes de, depois que os militares saíram do poder, promover o esquecimento dos graves fatos ocorridos durante a ditadura e constata que, finalmente, o esquecimento está sendo combatido por diversas instituições e pessoas, sobretudo pelos jovens.\n\nFilme produzido pelo Instituto Macuco, no âmbito do projeto Marcas da Memória, do Ministério da Justiça." },
  { title: "O Homem da Capa Preta", youtubeId: "gOy2zOcWwvY", director: "Sergio Rezende", genre: "Biografia, crime e drama", country: "Brasil", year: "1986", duration: "120 min", description: "Tenório Cavalcanti, polêmico e violento político da Baixada Fluminense, desafia os poderosos da região, nos anos 50 e 60. Com uma metralhadora e usando capa preta e cartola, faz justiça com as próprias mãos." },
  { title: "O País de São Saruê", youtubeId: "yBYHhBhr15U", description: null },
  { title: "O Papel do Eucalipto", youtubeId: "6eU_59vY9ds", description: null },
  { title: "O Relato da Tortura", youtubeId: "V2sFmMjP51E", director: "Haskell Wexler e Saul Landau", genre: "Documentário", country: "Chile", year: "1971", description: "Relato da tortura (Brazil: a report on torture), rodado no Chile, é um documentário produzido em 1971 pelo cineasta norte-americano Haskell Wexler que conta com depoimentos de brasileiros torturados e recém-exilados no Chile. Captando entrevistas de alguns dos 70 brasileiros levados àquele país em janeiro daquele ano em troca do embaixador suiço Giovanni Bucher, sequestrado no final de 1970 no Rio de Janeiro pelo guerrilha armada da VPR, mostra, entre depoimentos pessoais de sevícias sofridas pelos presos no Brasil, a simulação de torturas encenadas por eles mesmos, como a do pau de arara. O filme, realizado com câmera na mão e de fotografia crua, foi rodado com a colaboração de Saul Landau e Haskell Wexler." },
  { title: "Os Advogados contra a Ditadura: Por uma Questão de Justiça", youtubeId: "k4x6vOFwy0g", director: "Silvio Tendler", genre: "Documentário", country: "Brasil", year: "2013", duration: "130 min", description: "O documentário propõe uma profunda reflexão sobra a época em questão, relembrando, através de depoimentos e registros de arquivos, a relevante e ativa participação dos advogados contra as imposições do autoritarismo e na luta pela liberdade." },
  { title: "Os Militares que Disseram Não", youtubeId: "w-4pZLEtots", director: "Silvio Tendler", genre: "Documentário", country: "Brasil", year: "2014", duration: "88 min", description: "Por meio de depoimentos e registros de arquivos, o filme resgata as memórias sufocadas e despercebidas de oficiais militares cassados, torturados e mortos por defenderem a ordem constitucional e uma sociedade democrática." },
];

async function main() {
  const importer = await prisma.user.findUnique({ where: { email: "importacao-acervo@lace.local" } });
  if (!importer) throw new Error("Usuário de importação do acervo não encontrado.");
  for (const film of films) {
    const externalUrl = film.externalUrl || `https://www.youtube.com/watch?v=${film.youtubeId}`;
    const metadata = { youtubeId: film.youtubeId, vimeoId: film.vimeoId, videoProvider: film.vimeoId ? "vimeo" : "youtube", imageUrl: film.youtubeId ? `https://img.youtube.com/vi/${film.youtubeId}/hqdefault.jpg` : null, director: film.director, genre: film.genre, country: film.country, year: film.year, duration: film.duration };
    const existing = await prisma.content.findFirst({ where: { type: "FILM", title: film.title } });
    const data = { title: film.title, description: film.description, type: "FILM", researcherName: "Equipe LACE", externalUrl, metadata, published: true, createdById: importer.id };
    if (existing) await prisma.content.update({ where: { id: existing.id }, data });
    else await prisma.content.create({ data });
  }
  console.log(`${films.length} filmes da letra O importados.`);
}

main().catch((error) => { console.error(error); process.exitCode = 1; }).finally(() => prisma.$disconnect());
